### ISSUE TITLE
Rate limiting issue? 

### ISSUE THREAD

**Issue by nytyp** [FThompson/BBCSoundDownloader#2] opened 2018-11-16 19:15 UTC
No matter what thread count I set in the script, it caps out randomly between 1 and 5 files.  Once those 1-5 samples are downloaded, i have to restart the script to grab more. What is causing this? Is the BBC site rate limiting in some way? Why does the script not loop to attempt more after the first set of THREAD_COUNT samples have been downloaded? 

<img width="1407" alt="screen shot 2018-11-16 at 11 14 00 am" src="https://user-images.githubusercontent.com/1312538/48642163-ee74e200-e990-11e8-8e1a-10dc272fa958.png">

**Comment by FThompson** [comment] 2018-11-16 20:19
What OS and Python version are you using? I'll see if I can replicate the issue. Otherwise I'll add additional debugging to the script.

**Comment by nytyp** [comment] 2018-11-16 20:21
macOS 10.13.6 — Python 3.7.1

**Comment by nytyp** [comment] 2018-11-16 20:21
thank you!!

**Comment by FThompson** [comment] 2018-11-17 10:41
I observe the same bug on macOS 10.13.3 with Python 3.7.1, working on identifying the problem.

**Comment by FThompson** [comment] 2018-11-18 12:53
Fixed in 8accc1040bcca077c740df894dc2d6a3ccc96910; ThreadPool's `imap_unordered` and `imap` hang on macOS for whatever reason, while `map` works fine. I also caught and fixed a bug caused by non-unique sample names. This latter update changes the filename format, so you can delete any previously downloaded samples.

**Closed by FThompson** 2018-11-18 12:53 UTC
